#[cfg(target_arch = "x86_64")]
#[derive(Debug, Clone, Copy)]
#[allow(non_camel_case_types)]
#[repr(i64)] // Same data representation as in the kernel
/// Syscall IDs for x86_64
/// Data extracted from: https://github.com/torvalds/linux/blob/v6.16-rc1/arch/x86/entry/syscalls/syscall_64.tbl, and generated with a vim macro.
pub enum SyscallID {
    read = 0,
    write = 1,
    open = 2,
    close = 3,
    stat = 4,
    fstat = 5,
    lstat = 6,
    poll = 7,
    lseek = 8,
    mmap = 9,
    mprotect = 10,
    munmap = 11,
    brk = 12,
    rt_sigaction_x64 = 13,
    rt_sigprocmask = 14,
    rt_sigreturn_x64 = 15,
    ioctl_x64 = 16,
    pread64 = 17,
    pwrite64 = 18,
    readv_x64 = 19,
    writev_x64 = 20,
    access = 21,
    pipe = 22,
    select = 23,
    sched_yield = 24,
    mremap = 25,
    msync = 26,
    mincore = 27,
    madvise = 28,
    shmget = 29,
    shmat = 30,
    shmctl = 31,
    dup = 32,
    dup2 = 33,
    pause = 34,
    nanosleep = 35,
    getitimer = 36,
    alarm = 37,
    setitimer = 38,
    getpid = 39,
    sendfile = 40,
    socket = 41,
    connect = 42,
    accept = 43,
    sendto = 44,
    recvfrom_x64 = 45,
    sendmsg_x64 = 46,
    recvmsg_x64 = 47,
    shutdown = 48,
    bind = 49,
    listen = 50,
    getsockname = 51,
    getpeername = 52,
    socketpair = 53,
    setsockopt_x64 = 54,
    getsockopt_x64 = 55,
    clone = 56,
    fork = 57,
    vfork = 58,
    execve_x64 = 59,
    exit = 60,
    wait4 = 61,
    kill = 62,
    uname = 63,
    semget = 64,
    semop = 65,
    semctl = 66,
    shmdt = 67,
    msgget = 68,
    msgsnd = 69,
    msgrcv = 70,
    msgctl = 71,
    fcntl = 72,
    flock = 73,
    fsync = 74,
    fdatasync = 75,
    truncate = 76,
    ftruncate = 77,
    getdents = 78,
    getcwd = 79,
    chdir = 80,
    fchdir = 81,
    rename = 82,
    mkdir = 83,
    rmdir = 84,
    creat = 85,
    link = 86,
    unlink = 87,
    symlink = 88,
    readlink = 89,
    chmod = 90,
    fchmod = 91,
    chown = 92,
    fchown = 93,
    lchown = 94,
    umask = 95,
    gettimeofday = 96,
    getrlimit = 97,
    getrusage = 98,
    sysinfo = 99,
    times = 100,
    ptrace_x64 = 101,
    getuid = 102,
    syslog = 103,
    getgid = 104,
    setuid = 105,
    setgid = 106,
    geteuid = 107,
    getegid = 108,
    setpgid = 109,
    getppid = 110,
    getpgrp = 111,
    setsid = 112,
    setreuid = 113,
    setregid = 114,
    getgroups = 115,
    setgroups = 116,
    setresuid = 117,
    getresuid = 118,
    setresgid = 119,
    getresgid = 120,
    getpgid = 121,
    setfsuid = 122,
    setfsgid = 123,
    getsid = 124,
    capget = 125,
    capset = 126,
    rt_sigpending_x64 = 127,
    rt_sigtimedwait_x64 = 128,
    rt_sigqueueinfo_x64 = 129,
    rt_sigsuspend = 130,
    sigaltstack_x64 = 131,
    utime = 132,
    mknod = 133,
    uselib_x64 = 134,
    personality = 135,
    ustat = 136,
    statfs = 137,
    fstatfs = 138,
    sysfs = 139,
    getpriority = 140,
    setpriority = 141,
    sched_setparam = 142,
    sched_getparam = 143,
    sched_setscheduler = 144,
    sched_getscheduler = 145,
    sched_get_priority_max = 146,
    sched_get_priority_min = 147,
    sched_rr_get_interval = 148,
    mlock = 149,
    munlock = 150,
    mlockall = 151,
    munlockall = 152,
    vhangup = 153,
    modify_ldt = 154,
    pivot_root = 155,
    _sysctl_x64 = 156,
    prctl = 157,
    arch_prctl = 158,
    adjtimex = 159,
    setrlimit = 160,
    chroot = 161,
    sync = 162,
    acct = 163,
    settimeofday = 164,
    mount = 165,
    umount2 = 166,
    swapon = 167,
    swapoff = 168,
    reboot = 169,
    sethostname = 170,
    setdomainname = 171,
    iopl = 172,
    ioperm = 173,
    create_module_x64 = 174,
    init_module = 175,
    delete_module = 176,
    get_kernel_syms_x64 = 177,
    query_module_x64 = 178,
    quotactl = 179,
    nfsservctl_x64 = 180,
    getpmsg = 181,
    putpmsg = 182,
    afs_syscall = 183,
    tuxcall = 184,
    security = 185,
    gettid = 186,
    readahead = 187,
    setxattr = 188,
    lsetxattr = 189,
    fsetxattr = 190,
    getxattr = 191,
    lgetxattr = 192,
    fgetxattr = 193,
    listxattr = 194,
    llistxattr = 195,
    flistxattr = 196,
    removexattr = 197,
    lremovexattr = 198,
    fremovexattr = 199,
    tkill = 200,
    time = 201,
    futex = 202,
    sched_setaffinity = 203,
    sched_getaffinity = 204,
    set_thread_area_x64 = 205,
    io_setup_x64 = 206,
    io_destroy = 207,
    io_getevents = 208,
    io_submit_x64 = 209,
    io_cancel = 210,
    get_thread_area_x64 = 211,
    lookup_dcookie = 212,
    epoll_create = 213,
    epoll_ctl_old_x64 = 214,
    epoll_wait_old_x64 = 215,
    remap_file_pages = 216,
    getdents64 = 217,
    set_tid_address = 218,
    restart_syscall = 219,
    semtimedop = 220,
    fadvise64 = 221,
    timer_create_x64 = 222,
    timer_settime = 223,
    timer_gettime = 224,
    timer_getoverrun = 225,
    timer_delete = 226,
    clock_settime = 227,
    clock_gettime = 228,
    clock_getres = 229,
    clock_nanosleep = 230,
    exit_group = 231,
    epoll_wait = 232,
    epoll_ctl = 233,
    tgkill = 234,
    utimes = 235,
    vserver_x64 = 236,
    mbind = 237,
    set_mempolicy = 238,
    get_mempolicy = 239,
    mq_open = 240,
    mq_unlink = 241,
    mq_timedsend = 242,
    mq_timedreceive = 243,
    mq_notify_x64 = 244,
    mq_getsetattr = 245,
    kexec_load_x64 = 246,
    waitid_x64 = 247,
    add_key = 248,
    request_key = 249,
    keyctl = 250,
    ioprio_set = 251,
    ioprio_get = 252,
    inotify_init = 253,
    inotify_add_watch = 254,
    inotify_rm_watch = 255,
    migrate_pages = 256,
    openat = 257,
    mkdirat = 258,
    mknodat = 259,
    fchownat = 260,
    futimesat = 261,
    newfstatat = 262,
    unlinkat = 263,
    renameat = 264,
    linkat = 265,
    symlinkat = 266,
    readlinkat = 267,
    fchmodat = 268,
    faccessat = 269,
    pselect6 = 270,
    ppoll = 271,
    unshare = 272,
    set_robust_list_x64 = 273,
    get_robust_list_x64 = 274,
    splice = 275,
    tee = 276,
    sync_file_range = 277,
    vmsplice_x64 = 278,
    move_pages_x64 = 279,
    utimensat = 280,
    epoll_pwait = 281,
    signalfd = 282,
    timerfd_create = 283,
    eventfd = 284,
    fallocate = 285,
    timerfd_settime = 286,
    timerfd_gettime = 287,
    accept4 = 288,
    signalfd4 = 289,
    eventfd2 = 290,
    epoll_create1 = 291,
    dup3 = 292,
    pipe2 = 293,
    inotify_init1 = 294,
    preadv_x64 = 295,
    pwritev_x64 = 296,
    rt_tgsigqueueinfo_x64 = 297,
    perf_event_open = 298,
    recvmmsg_x64 = 299,
    fanotify_init = 300,
    fanotify_mark = 301,
    prlimit64 = 302,
    name_to_handle_at = 303,
    open_by_handle_at = 304,
    clock_adjtime = 305,
    syncfs = 306,
    sendmmsg_x64 = 307,
    setns = 308,
    getcpu = 309,
    process_vm_readv_x64 = 310,
    process_vm_writev_x64 = 311,
    kcmp = 312,
    finit_module = 313,
    sched_setattr = 314,
    sched_getattr = 315,
    renameat2 = 316,
    seccomp = 317,
    getrandom = 318,
    memfd_create = 319,
    kexec_file_load = 320,
    bpf = 321,
    execveat_x64 = 322,
    userfaultfd = 323,
    membarrier = 324,
    mlock2 = 325,
    copy_file_range = 326,
    preadv2_x64 = 327,
    pwritev2_x64 = 328,
    pkey_mprotect = 329,
    pkey_alloc = 330,
    pkey_free = 331,
    statx = 332,
    io_pgetevents = 333,
    rseq = 334,
    uretprobe = 335,
    pidfd_send_signal = 424,
    io_uring_setup = 425,
    io_uring_enter = 426,
    io_uring_register = 427,
    open_tree = 428,
    move_mount = 429,
    fsopen = 430,
    fsconfig = 431,
    fsmount = 432,
    fspick = 433,
    pidfd_open = 434,
    clone3 = 435,
    close_range = 436,
    openat2 = 437,
    pidfd_getfd = 438,
    faccessat2 = 439,
    process_madvise = 440,
    epoll_pwait2 = 441,
    mount_setattr = 442,
    quotactl_fd = 443,
    landlock_create_ruleset = 444,
    landlock_add_rule = 445,
    landlock_restrict_self = 446,
    memfd_secret = 447,
    process_mrelease = 448,
    futex_waitv = 449,
    set_mempolicy_home_node = 450,
    cachestat = 451,
    fchmodat2 = 452,
    map_shadow_stack = 453,
    futex_wake = 454,
    futex_wait = 455,
    futex_requeue = 456,
    statmount = 457,
    listmount = 458,
    lsm_get_self_attr = 459,
    lsm_set_self_attr = 460,
    lsm_list_modules = 461,
    mseal = 462,
    setxattrat = 463,
    getxattrat = 464,
    listxattrat = 465,
    removexattrat = 466,
    open_tree_attr = 467,

    // Syscalls for x32
    rt_sigaction_x32 = 512,
    rt_sigreturn_x32 = 513,
    ioctl_x32 = 514,
    readv_x32 = 515,
    writev_x32 = 516,
    recvfrom_x32 = 517,
    sendmsg_x32 = 518,
    recvmsg_x32 = 519,
    execve_x32 = 520,
    ptrace_x32 = 521,
    rt_sigpending_x32 = 522,
    rt_sigtimedwait_x32 = 523,
    rt_sigqueueinfo_x32 = 524,
    sigaltstack_x32 = 525,
    timer_create_x32 = 526,
    mq_notify_x32 = 527,
    kexec_load_x32 = 528,
    waitid_x32 = 529,
    set_robust_list_x32 = 530,
    get_robust_list_x32 = 531,
    vmsplice_x32 = 532,
    move_pages_x32 = 533,
    preadv_x32 = 534,
    pwritev_x32 = 535,
    rt_tgsigqueueinfo_x32 = 536,
    recvmmsg_x32 = 537,
    sendmmsg_x32 = 538,
    process_vm_readv_x32 = 539,
    process_vm_writev_x32 = 540,
    setsockopt_x32 = 541,
    getsockopt_x32 = 542,
    io_setup_x32 = 543,
    io_submit_x32 = 544,
    execveat_x32 = 545,
    preadv2_x32 = 546,
    pwritev2_x32 = 547,
}

/// Maximum number of syscalls
const MAX_NUM_SYSCALLS: usize = 600;

/// Table for mapping a syscall to its name
const SYSCALL_ID_TO_NAME_TABLE: [&str; MAX_NUM_SYSCALLS] = build_syscall_id_to_name_table();

/// Table for mapping an integer to a syscall
const ID_TO_SYSCALL_TABLE: [Option<SyscallID>; MAX_NUM_SYSCALLS] = build_id_to_syscall_table();

impl SyscallID {
    pub const fn as_str(self) -> &'static str {
        // assume table has been built correctly
        SYSCALL_ID_TO_NAME_TABLE[self as usize]
    }
}

#[cfg(target_arch = "x86_64")]
impl TryFrom<i64> for SyscallID {
    type Error = ();

    fn try_from(value: i64) -> Result<Self, Self::Error> {
        if value < 0 || value as usize > ID_TO_SYSCALL_TABLE.len() {
            return Err(());
        }
        ID_TO_SYSCALL_TABLE[value as usize].ok_or(())
    }
}

#[cfg(target_arch = "x86_64")]
const fn build_syscall_id_to_name_table() -> [&'static str; MAX_NUM_SYSCALLS] {
    // Data extracted from: https://github.com/torvalds/linux/blob/v6.16-rc1/arch/x86/entry/syscalls/syscall_64.tbl
    let mut t: [&str; MAX_NUM_SYSCALLS] = [""; MAX_NUM_SYSCALLS];

    t[SyscallID::read as usize] = "read";
    t[SyscallID::write as usize] = "write";
    t[SyscallID::open as usize] = "open";
    t[SyscallID::close as usize] = "close";
    t[SyscallID::stat as usize] = "stat";
    t[SyscallID::fstat as usize] = "fstat";
    t[SyscallID::lstat as usize] = "lstat";
    t[SyscallID::poll as usize] = "poll";
    t[SyscallID::lseek as usize] = "lseek";
    t[SyscallID::mmap as usize] = "mmap";
    t[SyscallID::mprotect as usize] = "mprotect";
    t[SyscallID::munmap as usize] = "munmap";
    t[SyscallID::brk as usize] = "brk";
    t[SyscallID::rt_sigaction_x64 as usize] = "rt_sigaction (x64)";
    t[SyscallID::rt_sigprocmask as usize] = "rt_sigprocmask";
    t[SyscallID::rt_sigreturn_x64 as usize] = "rt_sigreturn (x64)";
    t[SyscallID::ioctl_x64 as usize] = "ioctl (x64)";
    t[SyscallID::pread64 as usize] = "pread64";
    t[SyscallID::pwrite64 as usize] = "pwrite64";
    t[SyscallID::readv_x64 as usize] = "readv (x64)";
    t[SyscallID::writev_x64 as usize] = "writev (x64)";
    t[SyscallID::access as usize] = "access";
    t[SyscallID::pipe as usize] = "pipe";
    t[SyscallID::select as usize] = "select";
    t[SyscallID::sched_yield as usize] = "sched_yield";
    t[SyscallID::mremap as usize] = "mremap";
    t[SyscallID::msync as usize] = "msync";
    t[SyscallID::mincore as usize] = "mincore";
    t[SyscallID::madvise as usize] = "madvise";
    t[SyscallID::shmget as usize] = "shmget";
    t[SyscallID::shmat as usize] = "shmat";
    t[SyscallID::shmctl as usize] = "shmctl";
    t[SyscallID::dup as usize] = "dup";
    t[SyscallID::dup2 as usize] = "dup2";
    t[SyscallID::pause as usize] = "pause";
    t[SyscallID::nanosleep as usize] = "nanosleep";
    t[SyscallID::getitimer as usize] = "getitimer";
    t[SyscallID::alarm as usize] = "alarm";
    t[SyscallID::setitimer as usize] = "setitimer";
    t[SyscallID::getpid as usize] = "getpid";
    t[SyscallID::sendfile as usize] = "sendfile";
    t[SyscallID::socket as usize] = "socket";
    t[SyscallID::connect as usize] = "connect";
    t[SyscallID::accept as usize] = "accept";
    t[SyscallID::sendto as usize] = "sendto";
    t[SyscallID::recvfrom_x64 as usize] = "recvfrom (x64)";
    t[SyscallID::sendmsg_x64 as usize] = "sendmsg (x64)";
    t[SyscallID::recvmsg_x64 as usize] = "recvmsg (x64)";
    t[SyscallID::shutdown as usize] = "shutdown";
    t[SyscallID::bind as usize] = "bind";
    t[SyscallID::listen as usize] = "listen";
    t[SyscallID::getsockname as usize] = "getsockname";
    t[SyscallID::getpeername as usize] = "getpeername";
    t[SyscallID::socketpair as usize] = "socketpair";
    t[SyscallID::setsockopt_x64 as usize] = "setsockopt (x64)";
    t[SyscallID::getsockopt_x64 as usize] = "getsockopt (x64)";
    t[SyscallID::clone as usize] = "clone";
    t[SyscallID::fork as usize] = "fork";
    t[SyscallID::vfork as usize] = "vfork";
    t[SyscallID::execve_x64 as usize] = "execve (x64)";
    t[SyscallID::exit as usize] = "exit";
    t[SyscallID::wait4 as usize] = "wait4";
    t[SyscallID::kill as usize] = "kill";
    t[SyscallID::uname as usize] = "uname";
    t[SyscallID::semget as usize] = "semget";
    t[SyscallID::semop as usize] = "semop";
    t[SyscallID::semctl as usize] = "semctl";
    t[SyscallID::shmdt as usize] = "shmdt";
    t[SyscallID::msgget as usize] = "msgget";
    t[SyscallID::msgsnd as usize] = "msgsnd";
    t[SyscallID::msgrcv as usize] = "msgrcv";
    t[SyscallID::msgctl as usize] = "msgctl";
    t[SyscallID::fcntl as usize] = "fcntl";
    t[SyscallID::flock as usize] = "flock";
    t[SyscallID::fsync as usize] = "fsync";
    t[SyscallID::fdatasync as usize] = "fdatasync";
    t[SyscallID::truncate as usize] = "truncate";
    t[SyscallID::ftruncate as usize] = "ftruncate";
    t[SyscallID::getdents as usize] = "getdents";
    t[SyscallID::getcwd as usize] = "getcwd";
    t[SyscallID::chdir as usize] = "chdir";
    t[SyscallID::fchdir as usize] = "fchdir";
    t[SyscallID::rename as usize] = "rename";
    t[SyscallID::mkdir as usize] = "mkdir";
    t[SyscallID::rmdir as usize] = "rmdir";
    t[SyscallID::creat as usize] = "creat";
    t[SyscallID::link as usize] = "link";
    t[SyscallID::unlink as usize] = "unlink";
    t[SyscallID::symlink as usize] = "symlink";
    t[SyscallID::readlink as usize] = "readlink";
    t[SyscallID::chmod as usize] = "chmod";
    t[SyscallID::fchmod as usize] = "fchmod";
    t[SyscallID::chown as usize] = "chown";
    t[SyscallID::fchown as usize] = "fchown";
    t[SyscallID::lchown as usize] = "lchown";
    t[SyscallID::umask as usize] = "umask";
    t[SyscallID::gettimeofday as usize] = "gettimeofday";
    t[SyscallID::getrlimit as usize] = "getrlimit";
    t[SyscallID::getrusage as usize] = "getrusage";
    t[SyscallID::sysinfo as usize] = "sysinfo";
    t[SyscallID::times as usize] = "times";
    t[SyscallID::ptrace_x64 as usize] = "ptrace (x64)";
    t[SyscallID::getuid as usize] = "getuid";
    t[SyscallID::syslog as usize] = "syslog";
    t[SyscallID::getgid as usize] = "getgid";
    t[SyscallID::setuid as usize] = "setuid";
    t[SyscallID::setgid as usize] = "setgid";
    t[SyscallID::geteuid as usize] = "geteuid";
    t[SyscallID::getegid as usize] = "getegid";
    t[SyscallID::setpgid as usize] = "setpgid";
    t[SyscallID::getppid as usize] = "getppid";
    t[SyscallID::getpgrp as usize] = "getpgrp";
    t[SyscallID::setsid as usize] = "setsid";
    t[SyscallID::setreuid as usize] = "setreuid";
    t[SyscallID::setregid as usize] = "setregid";
    t[SyscallID::getgroups as usize] = "getgroups";
    t[SyscallID::setgroups as usize] = "setgroups";
    t[SyscallID::setresuid as usize] = "setresuid";
    t[SyscallID::getresuid as usize] = "getresuid";
    t[SyscallID::setresgid as usize] = "setresgid";
    t[SyscallID::getresgid as usize] = "getresgid";
    t[SyscallID::getpgid as usize] = "getpgid";
    t[SyscallID::setfsuid as usize] = "setfsuid";
    t[SyscallID::setfsgid as usize] = "setfsgid";
    t[SyscallID::getsid as usize] = "getsid";
    t[SyscallID::capget as usize] = "capget";
    t[SyscallID::capset as usize] = "capset";
    t[SyscallID::rt_sigpending_x64 as usize] = "rt_sigpending (x64)";
    t[SyscallID::rt_sigtimedwait_x64 as usize] = "rt_sigtimedwait (x64)";
    t[SyscallID::rt_sigqueueinfo_x64 as usize] = "rt_sigqueueinfo (x64)";
    t[SyscallID::rt_sigsuspend as usize] = "rt_sigsuspend";
    t[SyscallID::sigaltstack_x64 as usize] = "sigaltstack (x64)";
    t[SyscallID::utime as usize] = "utime";
    t[SyscallID::mknod as usize] = "mknod";
    t[SyscallID::uselib_x64 as usize] = "uselib (x64)";
    t[SyscallID::personality as usize] = "personality";
    t[SyscallID::ustat as usize] = "ustat";
    t[SyscallID::statfs as usize] = "statfs";
    t[SyscallID::fstatfs as usize] = "fstatfs";
    t[SyscallID::sysfs as usize] = "sysfs";
    t[SyscallID::getpriority as usize] = "getpriority";
    t[SyscallID::setpriority as usize] = "setpriority";
    t[SyscallID::sched_setparam as usize] = "sched_setparam";
    t[SyscallID::sched_getparam as usize] = "sched_getparam";
    t[SyscallID::sched_setscheduler as usize] = "sched_setscheduler";
    t[SyscallID::sched_getscheduler as usize] = "sched_getscheduler";
    t[SyscallID::sched_get_priority_max as usize] = "sched_get_priority_max";
    t[SyscallID::sched_get_priority_min as usize] = "sched_get_priority_min";
    t[SyscallID::sched_rr_get_interval as usize] = "sched_rr_get_interval";
    t[SyscallID::mlock as usize] = "mlock";
    t[SyscallID::munlock as usize] = "munlock";
    t[SyscallID::mlockall as usize] = "mlockall";
    t[SyscallID::munlockall as usize] = "munlockall";
    t[SyscallID::vhangup as usize] = "vhangup";
    t[SyscallID::modify_ldt as usize] = "modify_ldt";
    t[SyscallID::pivot_root as usize] = "pivot_root";
    t[SyscallID::_sysctl_x64 as usize] = "_sysctl (x64)";
    t[SyscallID::prctl as usize] = "prctl";
    t[SyscallID::arch_prctl as usize] = "arch_prctl";
    t[SyscallID::adjtimex as usize] = "adjtimex";
    t[SyscallID::setrlimit as usize] = "setrlimit";
    t[SyscallID::chroot as usize] = "chroot";
    t[SyscallID::sync as usize] = "sync";
    t[SyscallID::acct as usize] = "acct";
    t[SyscallID::settimeofday as usize] = "settimeofday";
    t[SyscallID::mount as usize] = "mount";
    t[SyscallID::umount2 as usize] = "umount2";
    t[SyscallID::swapon as usize] = "swapon";
    t[SyscallID::swapoff as usize] = "swapoff";
    t[SyscallID::reboot as usize] = "reboot";
    t[SyscallID::sethostname as usize] = "sethostname";
    t[SyscallID::setdomainname as usize] = "setdomainname";
    t[SyscallID::iopl as usize] = "iopl";
    t[SyscallID::ioperm as usize] = "ioperm";
    t[SyscallID::create_module_x64 as usize] = "create_module (x64)";
    t[SyscallID::init_module as usize] = "init_module";
    t[SyscallID::delete_module as usize] = "delete_module";
    t[SyscallID::get_kernel_syms_x64 as usize] = "get_kernel_syms (x64)";
    t[SyscallID::query_module_x64 as usize] = "query_module (x64)";
    t[SyscallID::quotactl as usize] = "quotactl";
    t[SyscallID::nfsservctl_x64 as usize] = "nfsservctl (x64)";
    t[SyscallID::getpmsg as usize] = "getpmsg";
    t[SyscallID::putpmsg as usize] = "putpmsg";
    t[SyscallID::afs_syscall as usize] = "afs_syscall";
    t[SyscallID::tuxcall as usize] = "tuxcall";
    t[SyscallID::security as usize] = "security";
    t[SyscallID::gettid as usize] = "gettid";
    t[SyscallID::readahead as usize] = "readahead";
    t[SyscallID::setxattr as usize] = "setxattr";
    t[SyscallID::lsetxattr as usize] = "lsetxattr";
    t[SyscallID::fsetxattr as usize] = "fsetxattr";
    t[SyscallID::getxattr as usize] = "getxattr";
    t[SyscallID::lgetxattr as usize] = "lgetxattr";
    t[SyscallID::fgetxattr as usize] = "fgetxattr";
    t[SyscallID::listxattr as usize] = "listxattr";
    t[SyscallID::llistxattr as usize] = "llistxattr";
    t[SyscallID::flistxattr as usize] = "flistxattr";
    t[SyscallID::removexattr as usize] = "removexattr";
    t[SyscallID::lremovexattr as usize] = "lremovexattr";
    t[SyscallID::fremovexattr as usize] = "fremovexattr";
    t[SyscallID::tkill as usize] = "tkill";
    t[SyscallID::time as usize] = "time";
    t[SyscallID::futex as usize] = "futex";
    t[SyscallID::sched_setaffinity as usize] = "sched_setaffinity";
    t[SyscallID::sched_getaffinity as usize] = "sched_getaffinity";
    t[SyscallID::set_thread_area_x64 as usize] = "set_thread_area (x64)";
    t[SyscallID::io_setup_x64 as usize] = "io_setup (x64)";
    t[SyscallID::io_destroy as usize] = "io_destroy";
    t[SyscallID::io_getevents as usize] = "io_getevents";
    t[SyscallID::io_submit_x64 as usize] = "io_submit (x64)";
    t[SyscallID::io_cancel as usize] = "io_cancel";
    t[SyscallID::get_thread_area_x64 as usize] = "get_thread_area (x64)";
    t[SyscallID::lookup_dcookie as usize] = "lookup_dcookie";
    t[SyscallID::epoll_create as usize] = "epoll_create";
    t[SyscallID::epoll_ctl_old_x64 as usize] = "epoll_ctl_old (x64)";
    t[SyscallID::epoll_wait_old_x64 as usize] = "epoll_wait_old (x64)";
    t[SyscallID::remap_file_pages as usize] = "remap_file_pages";
    t[SyscallID::getdents64 as usize] = "getdents64";
    t[SyscallID::set_tid_address as usize] = "set_tid_address";
    t[SyscallID::restart_syscall as usize] = "restart_syscall";
    t[SyscallID::semtimedop as usize] = "semtimedop";
    t[SyscallID::fadvise64 as usize] = "fadvise64";
    t[SyscallID::timer_create_x64 as usize] = "timer_create (x64)";
    t[SyscallID::timer_settime as usize] = "timer_settime";
    t[SyscallID::timer_gettime as usize] = "timer_gettime";
    t[SyscallID::timer_getoverrun as usize] = "timer_getoverrun";
    t[SyscallID::timer_delete as usize] = "timer_delete";
    t[SyscallID::clock_settime as usize] = "clock_settime";
    t[SyscallID::clock_gettime as usize] = "clock_gettime";
    t[SyscallID::clock_getres as usize] = "clock_getres";
    t[SyscallID::clock_nanosleep as usize] = "clock_nanosleep";
    t[SyscallID::exit_group as usize] = "exit_group";
    t[SyscallID::epoll_wait as usize] = "epoll_wait";
    t[SyscallID::epoll_ctl as usize] = "epoll_ctl";
    t[SyscallID::tgkill as usize] = "tgkill";
    t[SyscallID::utimes as usize] = "utimes";
    t[SyscallID::vserver_x64 as usize] = "vserver (x64)";
    t[SyscallID::mbind as usize] = "mbind";
    t[SyscallID::set_mempolicy as usize] = "set_mempolicy";
    t[SyscallID::get_mempolicy as usize] = "get_mempolicy";
    t[SyscallID::mq_open as usize] = "mq_open";
    t[SyscallID::mq_unlink as usize] = "mq_unlink";
    t[SyscallID::mq_timedsend as usize] = "mq_timedsend";
    t[SyscallID::mq_timedreceive as usize] = "mq_timedreceive";
    t[SyscallID::mq_notify_x64 as usize] = "mq_notify (x64)";
    t[SyscallID::mq_getsetattr as usize] = "mq_getsetattr";
    t[SyscallID::kexec_load_x64 as usize] = "kexec_load (x64)";
    t[SyscallID::waitid_x64 as usize] = "waitid (x64)";
    t[SyscallID::add_key as usize] = "add_key";
    t[SyscallID::request_key as usize] = "request_key";
    t[SyscallID::keyctl as usize] = "keyctl";
    t[SyscallID::ioprio_set as usize] = "ioprio_set";
    t[SyscallID::ioprio_get as usize] = "ioprio_get";
    t[SyscallID::inotify_init as usize] = "inotify_init";
    t[SyscallID::inotify_add_watch as usize] = "inotify_add_watch";
    t[SyscallID::inotify_rm_watch as usize] = "inotify_rm_watch";
    t[SyscallID::migrate_pages as usize] = "migrate_pages";
    t[SyscallID::openat as usize] = "openat";
    t[SyscallID::mkdirat as usize] = "mkdirat";
    t[SyscallID::mknodat as usize] = "mknodat";
    t[SyscallID::fchownat as usize] = "fchownat";
    t[SyscallID::futimesat as usize] = "futimesat";
    t[SyscallID::newfstatat as usize] = "newfstatat";
    t[SyscallID::unlinkat as usize] = "unlinkat";
    t[SyscallID::renameat as usize] = "renameat";
    t[SyscallID::linkat as usize] = "linkat";
    t[SyscallID::symlinkat as usize] = "symlinkat";
    t[SyscallID::readlinkat as usize] = "readlinkat";
    t[SyscallID::fchmodat as usize] = "fchmodat";
    t[SyscallID::faccessat as usize] = "faccessat";
    t[SyscallID::pselect6 as usize] = "pselect6";
    t[SyscallID::ppoll as usize] = "ppoll";
    t[SyscallID::unshare as usize] = "unshare";
    t[SyscallID::set_robust_list_x64 as usize] = "set_robust_list (x64)";
    t[SyscallID::get_robust_list_x64 as usize] = "get_robust_list (x64)";
    t[SyscallID::splice as usize] = "splice";
    t[SyscallID::tee as usize] = "tee";
    t[SyscallID::sync_file_range as usize] = "sync_file_range";
    t[SyscallID::vmsplice_x64 as usize] = "vmsplice (x64)";
    t[SyscallID::move_pages_x64 as usize] = "move_pages (x64)";
    t[SyscallID::utimensat as usize] = "utimensat";
    t[SyscallID::epoll_pwait as usize] = "epoll_pwait";
    t[SyscallID::signalfd as usize] = "signalfd";
    t[SyscallID::timerfd_create as usize] = "timerfd_create";
    t[SyscallID::eventfd as usize] = "eventfd";
    t[SyscallID::fallocate as usize] = "fallocate";
    t[SyscallID::timerfd_settime as usize] = "timerfd_settime";
    t[SyscallID::timerfd_gettime as usize] = "timerfd_gettime";
    t[SyscallID::accept4 as usize] = "accept4";
    t[SyscallID::signalfd4 as usize] = "signalfd4";
    t[SyscallID::eventfd2 as usize] = "eventfd2";
    t[SyscallID::epoll_create1 as usize] = "epoll_create1";
    t[SyscallID::dup3 as usize] = "dup3";
    t[SyscallID::pipe2 as usize] = "pipe2";
    t[SyscallID::inotify_init1 as usize] = "inotify_init1";
    t[SyscallID::preadv_x64 as usize] = "preadv (x64)";
    t[SyscallID::pwritev_x64 as usize] = "pwritev (x64)";
    t[SyscallID::rt_tgsigqueueinfo_x64 as usize] = "rt_tgsigqueueinfo (x64)";
    t[SyscallID::perf_event_open as usize] = "perf_event_open";
    t[SyscallID::recvmmsg_x64 as usize] = "recvmmsg (x64)";
    t[SyscallID::fanotify_init as usize] = "fanotify_init";
    t[SyscallID::fanotify_mark as usize] = "fanotify_mark";
    t[SyscallID::prlimit64 as usize] = "prlimit64";
    t[SyscallID::name_to_handle_at as usize] = "name_to_handle_at";
    t[SyscallID::open_by_handle_at as usize] = "open_by_handle_at";
    t[SyscallID::clock_adjtime as usize] = "clock_adjtime";
    t[SyscallID::syncfs as usize] = "syncfs";
    t[SyscallID::sendmmsg_x64 as usize] = "sendmmsg (x64)";
    t[SyscallID::setns as usize] = "setns";
    t[SyscallID::getcpu as usize] = "getcpu";
    t[SyscallID::process_vm_readv_x64 as usize] = "process_vm_readv (x64)";
    t[SyscallID::process_vm_writev_x64 as usize] = "process_vm_writev (x64)";
    t[SyscallID::kcmp as usize] = "kcmp";
    t[SyscallID::finit_module as usize] = "finit_module";
    t[SyscallID::sched_setattr as usize] = "sched_setattr";
    t[SyscallID::sched_getattr as usize] = "sched_getattr";
    t[SyscallID::renameat2 as usize] = "renameat2";
    t[SyscallID::seccomp as usize] = "seccomp";
    t[SyscallID::getrandom as usize] = "getrandom";
    t[SyscallID::memfd_create as usize] = "memfd_create";
    t[SyscallID::kexec_file_load as usize] = "kexec_file_load";
    t[SyscallID::bpf as usize] = "bpf";
    t[SyscallID::execveat_x64 as usize] = "execveat (x64)";
    t[SyscallID::userfaultfd as usize] = "userfaultfd";
    t[SyscallID::membarrier as usize] = "membarrier";
    t[SyscallID::mlock2 as usize] = "mlock2";
    t[SyscallID::copy_file_range as usize] = "copy_file_range";
    t[SyscallID::preadv2_x64 as usize] = "preadv2 (x64)";
    t[SyscallID::pwritev2_x64 as usize] = "pwritev2 (x64)";
    t[SyscallID::pkey_mprotect as usize] = "pkey_mprotect";
    t[SyscallID::pkey_alloc as usize] = "pkey_alloc";
    t[SyscallID::pkey_free as usize] = "pkey_free";
    t[SyscallID::statx as usize] = "statx";
    t[SyscallID::io_pgetevents as usize] = "io_pgetevents";
    t[SyscallID::rseq as usize] = "rseq";
    t[SyscallID::uretprobe as usize] = "uretprobe";
    t[SyscallID::pidfd_send_signal as usize] = "pidfd_send_signal";
    t[SyscallID::io_uring_setup as usize] = "io_uring_setup";
    t[SyscallID::io_uring_enter as usize] = "io_uring_enter";
    t[SyscallID::io_uring_register as usize] = "io_uring_register";
    t[SyscallID::open_tree as usize] = "open_tree";
    t[SyscallID::move_mount as usize] = "move_mount";
    t[SyscallID::fsopen as usize] = "fsopen";
    t[SyscallID::fsconfig as usize] = "fsconfig";
    t[SyscallID::fsmount as usize] = "fsmount";
    t[SyscallID::fspick as usize] = "fspick";
    t[SyscallID::pidfd_open as usize] = "pidfd_open";
    t[SyscallID::clone3 as usize] = "clone3";
    t[SyscallID::close_range as usize] = "close_range";
    t[SyscallID::openat2 as usize] = "openat2";
    t[SyscallID::pidfd_getfd as usize] = "pidfd_getfd";
    t[SyscallID::faccessat2 as usize] = "faccessat2";
    t[SyscallID::process_madvise as usize] = "process_madvise";
    t[SyscallID::epoll_pwait2 as usize] = "epoll_pwait2";
    t[SyscallID::mount_setattr as usize] = "mount_setattr";
    t[SyscallID::quotactl_fd as usize] = "quotactl_fd";
    t[SyscallID::landlock_create_ruleset as usize] = "landlock_create_ruleset";
    t[SyscallID::landlock_add_rule as usize] = "landlock_add_rule";
    t[SyscallID::landlock_restrict_self as usize] = "landlock_restrict_self";
    t[SyscallID::memfd_secret as usize] = "memfd_secret";
    t[SyscallID::process_mrelease as usize] = "process_mrelease";
    t[SyscallID::futex_waitv as usize] = "futex_waitv";
    t[SyscallID::set_mempolicy_home_node as usize] = "set_mempolicy_home_node";
    t[SyscallID::cachestat as usize] = "cachestat";
    t[SyscallID::fchmodat2 as usize] = "fchmodat2";
    t[SyscallID::map_shadow_stack as usize] = "map_shadow_stack";
    t[SyscallID::futex_wake as usize] = "futex_wake";
    t[SyscallID::futex_wait as usize] = "futex_wait";
    t[SyscallID::futex_requeue as usize] = "futex_requeue";
    t[SyscallID::statmount as usize] = "statmount";
    t[SyscallID::listmount as usize] = "listmount";
    t[SyscallID::lsm_get_self_attr as usize] = "lsm_get_self_attr";
    t[SyscallID::lsm_set_self_attr as usize] = "lsm_set_self_attr";
    t[SyscallID::lsm_list_modules as usize] = "lsm_list_modules";
    t[SyscallID::mseal as usize] = "mseal";
    t[SyscallID::setxattrat as usize] = "setxattrat";
    t[SyscallID::getxattrat as usize] = "getxattrat";
    t[SyscallID::listxattrat as usize] = "listxattrat";
    t[SyscallID::removexattrat as usize] = "removexattrat";
    t[SyscallID::open_tree_attr as usize] = "open_tree_attr";
    t[SyscallID::rt_sigaction_x32 as usize] = "rt_sigaction (x32)";
    t[SyscallID::rt_sigreturn_x32 as usize] = "rt_sigreturn (x32)";
    t[SyscallID::ioctl_x32 as usize] = "ioctl (x32)";
    t[SyscallID::readv_x32 as usize] = "readv (x32)";
    t[SyscallID::writev_x32 as usize] = "writev (x32)";
    t[SyscallID::recvfrom_x32 as usize] = "recvfrom (x32)";
    t[SyscallID::sendmsg_x32 as usize] = "sendmsg (x32)";
    t[SyscallID::recvmsg_x32 as usize] = "recvmsg (x32)";
    t[SyscallID::execve_x32 as usize] = "execve (x32)";
    t[SyscallID::ptrace_x32 as usize] = "ptrace (x32)";
    t[SyscallID::rt_sigpending_x32 as usize] = "rt_sigpending (x32)";
    t[SyscallID::rt_sigtimedwait_x32 as usize] = "rt_sigtimedwait (x32)";
    t[SyscallID::rt_sigqueueinfo_x32 as usize] = "rt_sigqueueinfo (x32)";
    t[SyscallID::sigaltstack_x32 as usize] = "sigaltstack (x32)";
    t[SyscallID::timer_create_x32 as usize] = "timer_create (x32)";
    t[SyscallID::mq_notify_x32 as usize] = "mq_notify (x32)";
    t[SyscallID::kexec_load_x32 as usize] = "kexec_load (x32)";
    t[SyscallID::waitid_x32 as usize] = "waitid (x32)";
    t[SyscallID::set_robust_list_x32 as usize] = "set_robust_list (x32)";
    t[SyscallID::get_robust_list_x32 as usize] = "get_robust_list (x32)";
    t[SyscallID::vmsplice_x32 as usize] = "vmsplice (x32)";
    t[SyscallID::move_pages_x32 as usize] = "move_pages (x32)";
    t[SyscallID::preadv_x32 as usize] = "preadv (x32)";
    t[SyscallID::pwritev_x32 as usize] = "pwritev (x32)";
    t[SyscallID::rt_tgsigqueueinfo_x32 as usize] = "rt_tgsigqueueinfo (x32)";
    t[SyscallID::recvmmsg_x32 as usize] = "recvmmsg (x32)";
    t[SyscallID::sendmmsg_x32 as usize] = "sendmmsg (x32)";
    t[SyscallID::process_vm_readv_x32 as usize] = "process_vm_readv (x32)";
    t[SyscallID::process_vm_writev_x32 as usize] = "process_vm_writev (x32)";
    t[SyscallID::setsockopt_x32 as usize] = "setsockopt (x32)";
    t[SyscallID::getsockopt_x32 as usize] = "getsockopt (x32)";
    t[SyscallID::io_setup_x32 as usize] = "io_setup (x32)";
    t[SyscallID::io_submit_x32 as usize] = "io_submit (x32)";
    t[SyscallID::execveat_x32 as usize] = "execveat (x32)";
    t[SyscallID::preadv2_x32 as usize] = "preadv2 (x32)";
    t[SyscallID::pwritev2_x32 as usize] = "pwritev2 (x32)";

    t
}

#[cfg(not(target_arch = "x86_64"))]
const fn build_syscall_table() -> [&'static str; MAX_NUM_SYSCALLS] {
    compile_error!("non supported architecture");
}

#[cfg(target_arch = "x86_64")]
const fn build_id_to_syscall_table() -> [Option<SyscallID>; MAX_NUM_SYSCALLS] {
    let mut t: [Option<SyscallID>; MAX_NUM_SYSCALLS] = [None; MAX_NUM_SYSCALLS];

    t[SyscallID::read as usize] = Some(SyscallID::read);
    t[SyscallID::write as usize] = Some(SyscallID::write);
    t[SyscallID::open as usize] = Some(SyscallID::open);
    t[SyscallID::close as usize] = Some(SyscallID::close);
    t[SyscallID::stat as usize] = Some(SyscallID::stat);
    t[SyscallID::fstat as usize] = Some(SyscallID::fstat);
    t[SyscallID::lstat as usize] = Some(SyscallID::lstat);
    t[SyscallID::poll as usize] = Some(SyscallID::poll);
    t[SyscallID::lseek as usize] = Some(SyscallID::lseek);
    t[SyscallID::mmap as usize] = Some(SyscallID::mmap);
    t[SyscallID::mprotect as usize] = Some(SyscallID::mprotect);
    t[SyscallID::munmap as usize] = Some(SyscallID::munmap);
    t[SyscallID::brk as usize] = Some(SyscallID::brk);
    t[SyscallID::rt_sigaction_x64 as usize] = Some(SyscallID::rt_sigaction_x64);
    t[SyscallID::rt_sigprocmask as usize] = Some(SyscallID::rt_sigprocmask);
    t[SyscallID::rt_sigreturn_x64 as usize] = Some(SyscallID::rt_sigreturn_x64);
    t[SyscallID::ioctl_x64 as usize] = Some(SyscallID::ioctl_x64);
    t[SyscallID::pread64 as usize] = Some(SyscallID::pread64);
    t[SyscallID::pwrite64 as usize] = Some(SyscallID::pwrite64);
    t[SyscallID::readv_x64 as usize] = Some(SyscallID::readv_x64);
    t[SyscallID::writev_x64 as usize] = Some(SyscallID::writev_x64);
    t[SyscallID::access as usize] = Some(SyscallID::access);
    t[SyscallID::pipe as usize] = Some(SyscallID::pipe);
    t[SyscallID::select as usize] = Some(SyscallID::select);
    t[SyscallID::sched_yield as usize] = Some(SyscallID::sched_yield);
    t[SyscallID::mremap as usize] = Some(SyscallID::mremap);
    t[SyscallID::msync as usize] = Some(SyscallID::msync);
    t[SyscallID::mincore as usize] = Some(SyscallID::mincore);
    t[SyscallID::madvise as usize] = Some(SyscallID::madvise);
    t[SyscallID::shmget as usize] = Some(SyscallID::shmget);
    t[SyscallID::shmat as usize] = Some(SyscallID::shmat);
    t[SyscallID::shmctl as usize] = Some(SyscallID::shmctl);
    t[SyscallID::dup as usize] = Some(SyscallID::dup);
    t[SyscallID::dup2 as usize] = Some(SyscallID::dup2);
    t[SyscallID::pause as usize] = Some(SyscallID::pause);
    t[SyscallID::nanosleep as usize] = Some(SyscallID::nanosleep);
    t[SyscallID::getitimer as usize] = Some(SyscallID::getitimer);
    t[SyscallID::alarm as usize] = Some(SyscallID::alarm);
    t[SyscallID::setitimer as usize] = Some(SyscallID::setitimer);
    t[SyscallID::getpid as usize] = Some(SyscallID::getpid);
    t[SyscallID::sendfile as usize] = Some(SyscallID::sendfile);
    t[SyscallID::socket as usize] = Some(SyscallID::socket);
    t[SyscallID::connect as usize] = Some(SyscallID::connect);
    t[SyscallID::accept as usize] = Some(SyscallID::accept);
    t[SyscallID::sendto as usize] = Some(SyscallID::sendto);
    t[SyscallID::recvfrom_x64 as usize] = Some(SyscallID::recvfrom_x64);
    t[SyscallID::sendmsg_x64 as usize] = Some(SyscallID::sendmsg_x64);
    t[SyscallID::recvmsg_x64 as usize] = Some(SyscallID::recvmsg_x64);
    t[SyscallID::shutdown as usize] = Some(SyscallID::shutdown);
    t[SyscallID::bind as usize] = Some(SyscallID::bind);
    t[SyscallID::listen as usize] = Some(SyscallID::listen);
    t[SyscallID::getsockname as usize] = Some(SyscallID::getsockname);
    t[SyscallID::getpeername as usize] = Some(SyscallID::getpeername);
    t[SyscallID::socketpair as usize] = Some(SyscallID::socketpair);
    t[SyscallID::setsockopt_x64 as usize] = Some(SyscallID::setsockopt_x64);
    t[SyscallID::getsockopt_x64 as usize] = Some(SyscallID::getsockopt_x64);
    t[SyscallID::clone as usize] = Some(SyscallID::clone);
    t[SyscallID::fork as usize] = Some(SyscallID::fork);
    t[SyscallID::vfork as usize] = Some(SyscallID::vfork);
    t[SyscallID::execve_x64 as usize] = Some(SyscallID::execve_x64);
    t[SyscallID::exit as usize] = Some(SyscallID::exit);
    t[SyscallID::wait4 as usize] = Some(SyscallID::wait4);
    t[SyscallID::kill as usize] = Some(SyscallID::kill);
    t[SyscallID::uname as usize] = Some(SyscallID::uname);
    t[SyscallID::semget as usize] = Some(SyscallID::semget);
    t[SyscallID::semop as usize] = Some(SyscallID::semop);
    t[SyscallID::semctl as usize] = Some(SyscallID::semctl);
    t[SyscallID::shmdt as usize] = Some(SyscallID::shmdt);
    t[SyscallID::msgget as usize] = Some(SyscallID::msgget);
    t[SyscallID::msgsnd as usize] = Some(SyscallID::msgsnd);
    t[SyscallID::msgrcv as usize] = Some(SyscallID::msgrcv);
    t[SyscallID::msgctl as usize] = Some(SyscallID::msgctl);
    t[SyscallID::fcntl as usize] = Some(SyscallID::fcntl);
    t[SyscallID::flock as usize] = Some(SyscallID::flock);
    t[SyscallID::fsync as usize] = Some(SyscallID::fsync);
    t[SyscallID::fdatasync as usize] = Some(SyscallID::fdatasync);
    t[SyscallID::truncate as usize] = Some(SyscallID::truncate);
    t[SyscallID::ftruncate as usize] = Some(SyscallID::ftruncate);
    t[SyscallID::getdents as usize] = Some(SyscallID::getdents);
    t[SyscallID::getcwd as usize] = Some(SyscallID::getcwd);
    t[SyscallID::chdir as usize] = Some(SyscallID::chdir);
    t[SyscallID::fchdir as usize] = Some(SyscallID::fchdir);
    t[SyscallID::rename as usize] = Some(SyscallID::rename);
    t[SyscallID::mkdir as usize] = Some(SyscallID::mkdir);
    t[SyscallID::rmdir as usize] = Some(SyscallID::rmdir);
    t[SyscallID::creat as usize] = Some(SyscallID::creat);
    t[SyscallID::link as usize] = Some(SyscallID::link);
    t[SyscallID::unlink as usize] = Some(SyscallID::unlink);
    t[SyscallID::symlink as usize] = Some(SyscallID::symlink);
    t[SyscallID::readlink as usize] = Some(SyscallID::readlink);
    t[SyscallID::chmod as usize] = Some(SyscallID::chmod);
    t[SyscallID::fchmod as usize] = Some(SyscallID::fchmod);
    t[SyscallID::chown as usize] = Some(SyscallID::chown);
    t[SyscallID::fchown as usize] = Some(SyscallID::fchown);
    t[SyscallID::lchown as usize] = Some(SyscallID::lchown);
    t[SyscallID::umask as usize] = Some(SyscallID::umask);
    t[SyscallID::gettimeofday as usize] = Some(SyscallID::gettimeofday);
    t[SyscallID::getrlimit as usize] = Some(SyscallID::getrlimit);
    t[SyscallID::getrusage as usize] = Some(SyscallID::getrusage);
    t[SyscallID::sysinfo as usize] = Some(SyscallID::sysinfo);
    t[SyscallID::times as usize] = Some(SyscallID::times);
    t[SyscallID::ptrace_x64 as usize] = Some(SyscallID::ptrace_x64);
    t[SyscallID::getuid as usize] = Some(SyscallID::getuid);
    t[SyscallID::syslog as usize] = Some(SyscallID::syslog);
    t[SyscallID::getgid as usize] = Some(SyscallID::getgid);
    t[SyscallID::setuid as usize] = Some(SyscallID::setuid);
    t[SyscallID::setgid as usize] = Some(SyscallID::setgid);
    t[SyscallID::geteuid as usize] = Some(SyscallID::geteuid);
    t[SyscallID::getegid as usize] = Some(SyscallID::getegid);
    t[SyscallID::setpgid as usize] = Some(SyscallID::setpgid);
    t[SyscallID::getppid as usize] = Some(SyscallID::getppid);
    t[SyscallID::getpgrp as usize] = Some(SyscallID::getpgrp);
    t[SyscallID::setsid as usize] = Some(SyscallID::setsid);
    t[SyscallID::setreuid as usize] = Some(SyscallID::setreuid);
    t[SyscallID::setregid as usize] = Some(SyscallID::setregid);
    t[SyscallID::getgroups as usize] = Some(SyscallID::getgroups);
    t[SyscallID::setgroups as usize] = Some(SyscallID::setgroups);
    t[SyscallID::setresuid as usize] = Some(SyscallID::setresuid);
    t[SyscallID::getresuid as usize] = Some(SyscallID::getresuid);
    t[SyscallID::setresgid as usize] = Some(SyscallID::setresgid);
    t[SyscallID::getresgid as usize] = Some(SyscallID::getresgid);
    t[SyscallID::getpgid as usize] = Some(SyscallID::getpgid);
    t[SyscallID::setfsuid as usize] = Some(SyscallID::setfsuid);
    t[SyscallID::setfsgid as usize] = Some(SyscallID::setfsgid);
    t[SyscallID::getsid as usize] = Some(SyscallID::getsid);
    t[SyscallID::capget as usize] = Some(SyscallID::capget);
    t[SyscallID::capset as usize] = Some(SyscallID::capset);
    t[SyscallID::rt_sigpending_x64 as usize] = Some(SyscallID::rt_sigpending_x64);
    t[SyscallID::rt_sigtimedwait_x64 as usize] = Some(SyscallID::rt_sigtimedwait_x64);
    t[SyscallID::rt_sigqueueinfo_x64 as usize] = Some(SyscallID::rt_sigqueueinfo_x64);
    t[SyscallID::rt_sigsuspend as usize] = Some(SyscallID::rt_sigsuspend);
    t[SyscallID::sigaltstack_x64 as usize] = Some(SyscallID::sigaltstack_x64);
    t[SyscallID::utime as usize] = Some(SyscallID::utime);
    t[SyscallID::mknod as usize] = Some(SyscallID::mknod);
    t[SyscallID::uselib_x64 as usize] = Some(SyscallID::uselib_x64);
    t[SyscallID::personality as usize] = Some(SyscallID::personality);
    t[SyscallID::ustat as usize] = Some(SyscallID::ustat);
    t[SyscallID::statfs as usize] = Some(SyscallID::statfs);
    t[SyscallID::fstatfs as usize] = Some(SyscallID::fstatfs);
    t[SyscallID::sysfs as usize] = Some(SyscallID::sysfs);
    t[SyscallID::getpriority as usize] = Some(SyscallID::getpriority);
    t[SyscallID::setpriority as usize] = Some(SyscallID::setpriority);
    t[SyscallID::sched_setparam as usize] = Some(SyscallID::sched_setparam);
    t[SyscallID::sched_getparam as usize] = Some(SyscallID::sched_getparam);
    t[SyscallID::sched_setscheduler as usize] = Some(SyscallID::sched_setscheduler);
    t[SyscallID::sched_getscheduler as usize] = Some(SyscallID::sched_getscheduler);
    t[SyscallID::sched_get_priority_max as usize] = Some(SyscallID::sched_get_priority_max);
    t[SyscallID::sched_get_priority_min as usize] = Some(SyscallID::sched_get_priority_min);
    t[SyscallID::sched_rr_get_interval as usize] = Some(SyscallID::sched_rr_get_interval);
    t[SyscallID::mlock as usize] = Some(SyscallID::mlock);
    t[SyscallID::munlock as usize] = Some(SyscallID::munlock);
    t[SyscallID::mlockall as usize] = Some(SyscallID::mlockall);
    t[SyscallID::munlockall as usize] = Some(SyscallID::munlockall);
    t[SyscallID::vhangup as usize] = Some(SyscallID::vhangup);
    t[SyscallID::modify_ldt as usize] = Some(SyscallID::modify_ldt);
    t[SyscallID::pivot_root as usize] = Some(SyscallID::pivot_root);
    t[SyscallID::_sysctl_x64 as usize] = Some(SyscallID::_sysctl_x64);
    t[SyscallID::prctl as usize] = Some(SyscallID::prctl);
    t[SyscallID::arch_prctl as usize] = Some(SyscallID::arch_prctl);
    t[SyscallID::adjtimex as usize] = Some(SyscallID::adjtimex);
    t[SyscallID::setrlimit as usize] = Some(SyscallID::setrlimit);
    t[SyscallID::chroot as usize] = Some(SyscallID::chroot);
    t[SyscallID::sync as usize] = Some(SyscallID::sync);
    t[SyscallID::acct as usize] = Some(SyscallID::acct);
    t[SyscallID::settimeofday as usize] = Some(SyscallID::settimeofday);
    t[SyscallID::mount as usize] = Some(SyscallID::mount);
    t[SyscallID::umount2 as usize] = Some(SyscallID::umount2);
    t[SyscallID::swapon as usize] = Some(SyscallID::swapon);
    t[SyscallID::swapoff as usize] = Some(SyscallID::swapoff);
    t[SyscallID::reboot as usize] = Some(SyscallID::reboot);
    t[SyscallID::sethostname as usize] = Some(SyscallID::sethostname);
    t[SyscallID::setdomainname as usize] = Some(SyscallID::setdomainname);
    t[SyscallID::iopl as usize] = Some(SyscallID::iopl);
    t[SyscallID::ioperm as usize] = Some(SyscallID::ioperm);
    t[SyscallID::create_module_x64 as usize] = Some(SyscallID::create_module_x64);
    t[SyscallID::init_module as usize] = Some(SyscallID::init_module);
    t[SyscallID::delete_module as usize] = Some(SyscallID::delete_module);
    t[SyscallID::get_kernel_syms_x64 as usize] = Some(SyscallID::get_kernel_syms_x64);
    t[SyscallID::query_module_x64 as usize] = Some(SyscallID::query_module_x64);
    t[SyscallID::quotactl as usize] = Some(SyscallID::quotactl);
    t[SyscallID::nfsservctl_x64 as usize] = Some(SyscallID::nfsservctl_x64);
    t[SyscallID::getpmsg as usize] = Some(SyscallID::getpmsg);
    t[SyscallID::putpmsg as usize] = Some(SyscallID::putpmsg);
    t[SyscallID::afs_syscall as usize] = Some(SyscallID::afs_syscall);
    t[SyscallID::tuxcall as usize] = Some(SyscallID::tuxcall);
    t[SyscallID::security as usize] = Some(SyscallID::security);
    t[SyscallID::gettid as usize] = Some(SyscallID::gettid);
    t[SyscallID::readahead as usize] = Some(SyscallID::readahead);
    t[SyscallID::setxattr as usize] = Some(SyscallID::setxattr);
    t[SyscallID::lsetxattr as usize] = Some(SyscallID::lsetxattr);
    t[SyscallID::fsetxattr as usize] = Some(SyscallID::fsetxattr);
    t[SyscallID::getxattr as usize] = Some(SyscallID::getxattr);
    t[SyscallID::lgetxattr as usize] = Some(SyscallID::lgetxattr);
    t[SyscallID::fgetxattr as usize] = Some(SyscallID::fgetxattr);
    t[SyscallID::listxattr as usize] = Some(SyscallID::listxattr);
    t[SyscallID::llistxattr as usize] = Some(SyscallID::llistxattr);
    t[SyscallID::flistxattr as usize] = Some(SyscallID::flistxattr);
    t[SyscallID::removexattr as usize] = Some(SyscallID::removexattr);
    t[SyscallID::lremovexattr as usize] = Some(SyscallID::lremovexattr);
    t[SyscallID::fremovexattr as usize] = Some(SyscallID::fremovexattr);
    t[SyscallID::tkill as usize] = Some(SyscallID::tkill);
    t[SyscallID::time as usize] = Some(SyscallID::time);
    t[SyscallID::futex as usize] = Some(SyscallID::futex);
    t[SyscallID::sched_setaffinity as usize] = Some(SyscallID::sched_setaffinity);
    t[SyscallID::sched_getaffinity as usize] = Some(SyscallID::sched_getaffinity);
    t[SyscallID::set_thread_area_x64 as usize] = Some(SyscallID::set_thread_area_x64);
    t[SyscallID::io_setup_x64 as usize] = Some(SyscallID::io_setup_x64);
    t[SyscallID::io_destroy as usize] = Some(SyscallID::io_destroy);
    t[SyscallID::io_getevents as usize] = Some(SyscallID::io_getevents);
    t[SyscallID::io_submit_x64 as usize] = Some(SyscallID::io_submit_x64);
    t[SyscallID::io_cancel as usize] = Some(SyscallID::io_cancel);
    t[SyscallID::get_thread_area_x64 as usize] = Some(SyscallID::get_thread_area_x64);
    t[SyscallID::lookup_dcookie as usize] = Some(SyscallID::lookup_dcookie);
    t[SyscallID::epoll_create as usize] = Some(SyscallID::epoll_create);
    t[SyscallID::epoll_ctl_old_x64 as usize] = Some(SyscallID::epoll_ctl_old_x64);
    t[SyscallID::epoll_wait_old_x64 as usize] = Some(SyscallID::epoll_wait_old_x64);
    t[SyscallID::remap_file_pages as usize] = Some(SyscallID::remap_file_pages);
    t[SyscallID::getdents64 as usize] = Some(SyscallID::getdents64);
    t[SyscallID::set_tid_address as usize] = Some(SyscallID::set_tid_address);
    t[SyscallID::restart_syscall as usize] = Some(SyscallID::restart_syscall);
    t[SyscallID::semtimedop as usize] = Some(SyscallID::semtimedop);
    t[SyscallID::fadvise64 as usize] = Some(SyscallID::fadvise64);
    t[SyscallID::timer_create_x64 as usize] = Some(SyscallID::timer_create_x64);
    t[SyscallID::timer_settime as usize] = Some(SyscallID::timer_settime);
    t[SyscallID::timer_gettime as usize] = Some(SyscallID::timer_gettime);
    t[SyscallID::timer_getoverrun as usize] = Some(SyscallID::timer_getoverrun);
    t[SyscallID::timer_delete as usize] = Some(SyscallID::timer_delete);
    t[SyscallID::clock_settime as usize] = Some(SyscallID::clock_settime);
    t[SyscallID::clock_gettime as usize] = Some(SyscallID::clock_gettime);
    t[SyscallID::clock_getres as usize] = Some(SyscallID::clock_getres);
    t[SyscallID::clock_nanosleep as usize] = Some(SyscallID::clock_nanosleep);
    t[SyscallID::exit_group as usize] = Some(SyscallID::exit_group);
    t[SyscallID::epoll_wait as usize] = Some(SyscallID::epoll_wait);
    t[SyscallID::epoll_ctl as usize] = Some(SyscallID::epoll_ctl);
    t[SyscallID::tgkill as usize] = Some(SyscallID::tgkill);
    t[SyscallID::utimes as usize] = Some(SyscallID::utimes);
    t[SyscallID::vserver_x64 as usize] = Some(SyscallID::vserver_x64);
    t[SyscallID::mbind as usize] = Some(SyscallID::mbind);
    t[SyscallID::set_mempolicy as usize] = Some(SyscallID::set_mempolicy);
    t[SyscallID::get_mempolicy as usize] = Some(SyscallID::get_mempolicy);
    t[SyscallID::mq_open as usize] = Some(SyscallID::mq_open);
    t[SyscallID::mq_unlink as usize] = Some(SyscallID::mq_unlink);
    t[SyscallID::mq_timedsend as usize] = Some(SyscallID::mq_timedsend);
    t[SyscallID::mq_timedreceive as usize] = Some(SyscallID::mq_timedreceive);
    t[SyscallID::mq_notify_x64 as usize] = Some(SyscallID::mq_notify_x64);
    t[SyscallID::mq_getsetattr as usize] = Some(SyscallID::mq_getsetattr);
    t[SyscallID::kexec_load_x64 as usize] = Some(SyscallID::kexec_load_x64);
    t[SyscallID::waitid_x64 as usize] = Some(SyscallID::waitid_x64);
    t[SyscallID::add_key as usize] = Some(SyscallID::add_key);
    t[SyscallID::request_key as usize] = Some(SyscallID::request_key);
    t[SyscallID::keyctl as usize] = Some(SyscallID::keyctl);
    t[SyscallID::ioprio_set as usize] = Some(SyscallID::ioprio_set);
    t[SyscallID::ioprio_get as usize] = Some(SyscallID::ioprio_get);
    t[SyscallID::inotify_init as usize] = Some(SyscallID::inotify_init);
    t[SyscallID::inotify_add_watch as usize] = Some(SyscallID::inotify_add_watch);
    t[SyscallID::inotify_rm_watch as usize] = Some(SyscallID::inotify_rm_watch);
    t[SyscallID::migrate_pages as usize] = Some(SyscallID::migrate_pages);
    t[SyscallID::openat as usize] = Some(SyscallID::openat);
    t[SyscallID::mkdirat as usize] = Some(SyscallID::mkdirat);
    t[SyscallID::mknodat as usize] = Some(SyscallID::mknodat);
    t[SyscallID::fchownat as usize] = Some(SyscallID::fchownat);
    t[SyscallID::futimesat as usize] = Some(SyscallID::futimesat);
    t[SyscallID::newfstatat as usize] = Some(SyscallID::newfstatat);
    t[SyscallID::unlinkat as usize] = Some(SyscallID::unlinkat);
    t[SyscallID::renameat as usize] = Some(SyscallID::renameat);
    t[SyscallID::linkat as usize] = Some(SyscallID::linkat);
    t[SyscallID::symlinkat as usize] = Some(SyscallID::symlinkat);
    t[SyscallID::readlinkat as usize] = Some(SyscallID::readlinkat);
    t[SyscallID::fchmodat as usize] = Some(SyscallID::fchmodat);
    t[SyscallID::faccessat as usize] = Some(SyscallID::faccessat);
    t[SyscallID::pselect6 as usize] = Some(SyscallID::pselect6);
    t[SyscallID::ppoll as usize] = Some(SyscallID::ppoll);
    t[SyscallID::unshare as usize] = Some(SyscallID::unshare);
    t[SyscallID::set_robust_list_x64 as usize] = Some(SyscallID::set_robust_list_x64);
    t[SyscallID::get_robust_list_x64 as usize] = Some(SyscallID::get_robust_list_x64);
    t[SyscallID::splice as usize] = Some(SyscallID::splice);
    t[SyscallID::tee as usize] = Some(SyscallID::tee);
    t[SyscallID::sync_file_range as usize] = Some(SyscallID::sync_file_range);
    t[SyscallID::vmsplice_x64 as usize] = Some(SyscallID::vmsplice_x64);
    t[SyscallID::move_pages_x64 as usize] = Some(SyscallID::move_pages_x64);
    t[SyscallID::utimensat as usize] = Some(SyscallID::utimensat);
    t[SyscallID::epoll_pwait as usize] = Some(SyscallID::epoll_pwait);
    t[SyscallID::signalfd as usize] = Some(SyscallID::signalfd);
    t[SyscallID::timerfd_create as usize] = Some(SyscallID::timerfd_create);
    t[SyscallID::eventfd as usize] = Some(SyscallID::eventfd);
    t[SyscallID::fallocate as usize] = Some(SyscallID::fallocate);
    t[SyscallID::timerfd_settime as usize] = Some(SyscallID::timerfd_settime);
    t[SyscallID::timerfd_gettime as usize] = Some(SyscallID::timerfd_gettime);
    t[SyscallID::accept4 as usize] = Some(SyscallID::accept4);
    t[SyscallID::signalfd4 as usize] = Some(SyscallID::signalfd4);
    t[SyscallID::eventfd2 as usize] = Some(SyscallID::eventfd2);
    t[SyscallID::epoll_create1 as usize] = Some(SyscallID::epoll_create1);
    t[SyscallID::dup3 as usize] = Some(SyscallID::dup3);
    t[SyscallID::pipe2 as usize] = Some(SyscallID::pipe2);
    t[SyscallID::inotify_init1 as usize] = Some(SyscallID::inotify_init1);
    t[SyscallID::preadv_x64 as usize] = Some(SyscallID::preadv_x64);
    t[SyscallID::pwritev_x64 as usize] = Some(SyscallID::pwritev_x64);
    t[SyscallID::rt_tgsigqueueinfo_x64 as usize] = Some(SyscallID::rt_tgsigqueueinfo_x64);
    t[SyscallID::perf_event_open as usize] = Some(SyscallID::perf_event_open);
    t[SyscallID::recvmmsg_x64 as usize] = Some(SyscallID::recvmmsg_x64);
    t[SyscallID::fanotify_init as usize] = Some(SyscallID::fanotify_init);
    t[SyscallID::fanotify_mark as usize] = Some(SyscallID::fanotify_mark);
    t[SyscallID::prlimit64 as usize] = Some(SyscallID::prlimit64);
    t[SyscallID::name_to_handle_at as usize] = Some(SyscallID::name_to_handle_at);
    t[SyscallID::open_by_handle_at as usize] = Some(SyscallID::open_by_handle_at);
    t[SyscallID::clock_adjtime as usize] = Some(SyscallID::clock_adjtime);
    t[SyscallID::syncfs as usize] = Some(SyscallID::syncfs);
    t[SyscallID::sendmmsg_x64 as usize] = Some(SyscallID::sendmmsg_x64);
    t[SyscallID::setns as usize] = Some(SyscallID::setns);
    t[SyscallID::getcpu as usize] = Some(SyscallID::getcpu);
    t[SyscallID::process_vm_readv_x64 as usize] = Some(SyscallID::process_vm_readv_x64);
    t[SyscallID::process_vm_writev_x64 as usize] = Some(SyscallID::process_vm_writev_x64);
    t[SyscallID::kcmp as usize] = Some(SyscallID::kcmp);
    t[SyscallID::finit_module as usize] = Some(SyscallID::finit_module);
    t[SyscallID::sched_setattr as usize] = Some(SyscallID::sched_setattr);
    t[SyscallID::sched_getattr as usize] = Some(SyscallID::sched_getattr);
    t[SyscallID::renameat2 as usize] = Some(SyscallID::renameat2);
    t[SyscallID::seccomp as usize] = Some(SyscallID::seccomp);
    t[SyscallID::getrandom as usize] = Some(SyscallID::getrandom);
    t[SyscallID::memfd_create as usize] = Some(SyscallID::memfd_create);
    t[SyscallID::kexec_file_load as usize] = Some(SyscallID::kexec_file_load);
    t[SyscallID::bpf as usize] = Some(SyscallID::bpf);
    t[SyscallID::execveat_x64 as usize] = Some(SyscallID::execveat_x64);
    t[SyscallID::userfaultfd as usize] = Some(SyscallID::userfaultfd);
    t[SyscallID::membarrier as usize] = Some(SyscallID::membarrier);
    t[SyscallID::mlock2 as usize] = Some(SyscallID::mlock2);
    t[SyscallID::copy_file_range as usize] = Some(SyscallID::copy_file_range);
    t[SyscallID::preadv2_x64 as usize] = Some(SyscallID::preadv2_x64);
    t[SyscallID::pwritev2_x64 as usize] = Some(SyscallID::pwritev2_x64);
    t[SyscallID::pkey_mprotect as usize] = Some(SyscallID::pkey_mprotect);
    t[SyscallID::pkey_alloc as usize] = Some(SyscallID::pkey_alloc);
    t[SyscallID::pkey_free as usize] = Some(SyscallID::pkey_free);
    t[SyscallID::statx as usize] = Some(SyscallID::statx);
    t[SyscallID::io_pgetevents as usize] = Some(SyscallID::io_pgetevents);
    t[SyscallID::rseq as usize] = Some(SyscallID::rseq);
    t[SyscallID::uretprobe as usize] = Some(SyscallID::uretprobe);
    t[SyscallID::pidfd_send_signal as usize] = Some(SyscallID::pidfd_send_signal);
    t[SyscallID::io_uring_setup as usize] = Some(SyscallID::io_uring_setup);
    t[SyscallID::io_uring_enter as usize] = Some(SyscallID::io_uring_enter);
    t[SyscallID::io_uring_register as usize] = Some(SyscallID::io_uring_register);
    t[SyscallID::open_tree as usize] = Some(SyscallID::open_tree);
    t[SyscallID::move_mount as usize] = Some(SyscallID::move_mount);
    t[SyscallID::fsopen as usize] = Some(SyscallID::fsopen);
    t[SyscallID::fsconfig as usize] = Some(SyscallID::fsconfig);
    t[SyscallID::fsmount as usize] = Some(SyscallID::fsmount);
    t[SyscallID::fspick as usize] = Some(SyscallID::fspick);
    t[SyscallID::pidfd_open as usize] = Some(SyscallID::pidfd_open);
    t[SyscallID::clone3 as usize] = Some(SyscallID::clone3);
    t[SyscallID::close_range as usize] = Some(SyscallID::close_range);
    t[SyscallID::openat2 as usize] = Some(SyscallID::openat2);
    t[SyscallID::pidfd_getfd as usize] = Some(SyscallID::pidfd_getfd);
    t[SyscallID::faccessat2 as usize] = Some(SyscallID::faccessat2);
    t[SyscallID::process_madvise as usize] = Some(SyscallID::process_madvise);
    t[SyscallID::epoll_pwait2 as usize] = Some(SyscallID::epoll_pwait2);
    t[SyscallID::mount_setattr as usize] = Some(SyscallID::mount_setattr);
    t[SyscallID::quotactl_fd as usize] = Some(SyscallID::quotactl_fd);
    t[SyscallID::landlock_create_ruleset as usize] = Some(SyscallID::landlock_create_ruleset);
    t[SyscallID::landlock_add_rule as usize] = Some(SyscallID::landlock_add_rule);
    t[SyscallID::landlock_restrict_self as usize] = Some(SyscallID::landlock_restrict_self);
    t[SyscallID::memfd_secret as usize] = Some(SyscallID::memfd_secret);
    t[SyscallID::process_mrelease as usize] = Some(SyscallID::process_mrelease);
    t[SyscallID::futex_waitv as usize] = Some(SyscallID::futex_waitv);
    t[SyscallID::set_mempolicy_home_node as usize] = Some(SyscallID::set_mempolicy_home_node);
    t[SyscallID::cachestat as usize] = Some(SyscallID::cachestat);
    t[SyscallID::fchmodat2 as usize] = Some(SyscallID::fchmodat2);
    t[SyscallID::map_shadow_stack as usize] = Some(SyscallID::map_shadow_stack);
    t[SyscallID::futex_wake as usize] = Some(SyscallID::futex_wake);
    t[SyscallID::futex_wait as usize] = Some(SyscallID::futex_wait);
    t[SyscallID::futex_requeue as usize] = Some(SyscallID::futex_requeue);
    t[SyscallID::statmount as usize] = Some(SyscallID::statmount);
    t[SyscallID::listmount as usize] = Some(SyscallID::listmount);
    t[SyscallID::lsm_get_self_attr as usize] = Some(SyscallID::lsm_get_self_attr);
    t[SyscallID::lsm_set_self_attr as usize] = Some(SyscallID::lsm_set_self_attr);
    t[SyscallID::lsm_list_modules as usize] = Some(SyscallID::lsm_list_modules);
    t[SyscallID::mseal as usize] = Some(SyscallID::mseal);
    t[SyscallID::setxattrat as usize] = Some(SyscallID::setxattrat);
    t[SyscallID::getxattrat as usize] = Some(SyscallID::getxattrat);
    t[SyscallID::listxattrat as usize] = Some(SyscallID::listxattrat);
    t[SyscallID::removexattrat as usize] = Some(SyscallID::removexattrat);
    t[SyscallID::open_tree_attr as usize] = Some(SyscallID::open_tree_attr);
    t[SyscallID::rt_sigaction_x32 as usize] = Some(SyscallID::rt_sigaction_x32);
    t[SyscallID::rt_sigreturn_x32 as usize] = Some(SyscallID::rt_sigreturn_x32);
    t[SyscallID::ioctl_x32 as usize] = Some(SyscallID::ioctl_x32);
    t[SyscallID::readv_x32 as usize] = Some(SyscallID::readv_x32);
    t[SyscallID::writev_x32 as usize] = Some(SyscallID::writev_x32);
    t[SyscallID::recvfrom_x32 as usize] = Some(SyscallID::recvfrom_x32);
    t[SyscallID::sendmsg_x32 as usize] = Some(SyscallID::sendmsg_x32);
    t[SyscallID::recvmsg_x32 as usize] = Some(SyscallID::recvmsg_x32);
    t[SyscallID::execve_x32 as usize] = Some(SyscallID::execve_x32);
    t[SyscallID::ptrace_x32 as usize] = Some(SyscallID::ptrace_x32);
    t[SyscallID::rt_sigpending_x32 as usize] = Some(SyscallID::rt_sigpending_x32);
    t[SyscallID::rt_sigtimedwait_x32 as usize] = Some(SyscallID::rt_sigtimedwait_x32);
    t[SyscallID::rt_sigqueueinfo_x32 as usize] = Some(SyscallID::rt_sigqueueinfo_x32);
    t[SyscallID::sigaltstack_x32 as usize] = Some(SyscallID::sigaltstack_x32);
    t[SyscallID::timer_create_x32 as usize] = Some(SyscallID::timer_create_x32);
    t[SyscallID::mq_notify_x32 as usize] = Some(SyscallID::mq_notify_x32);
    t[SyscallID::kexec_load_x32 as usize] = Some(SyscallID::kexec_load_x32);
    t[SyscallID::waitid_x32 as usize] = Some(SyscallID::waitid_x32);
    t[SyscallID::set_robust_list_x32 as usize] = Some(SyscallID::set_robust_list_x32);
    t[SyscallID::get_robust_list_x32 as usize] = Some(SyscallID::get_robust_list_x32);
    t[SyscallID::vmsplice_x32 as usize] = Some(SyscallID::vmsplice_x32);
    t[SyscallID::move_pages_x32 as usize] = Some(SyscallID::move_pages_x32);
    t[SyscallID::preadv_x32 as usize] = Some(SyscallID::preadv_x32);
    t[SyscallID::pwritev_x32 as usize] = Some(SyscallID::pwritev_x32);
    t[SyscallID::rt_tgsigqueueinfo_x32 as usize] = Some(SyscallID::rt_tgsigqueueinfo_x32);
    t[SyscallID::recvmmsg_x32 as usize] = Some(SyscallID::recvmmsg_x32);
    t[SyscallID::sendmmsg_x32 as usize] = Some(SyscallID::sendmmsg_x32);
    t[SyscallID::process_vm_readv_x32 as usize] = Some(SyscallID::process_vm_readv_x32);
    t[SyscallID::process_vm_writev_x32 as usize] = Some(SyscallID::process_vm_writev_x32);
    t[SyscallID::setsockopt_x32 as usize] = Some(SyscallID::setsockopt_x32);
    t[SyscallID::getsockopt_x32 as usize] = Some(SyscallID::getsockopt_x32);
    t[SyscallID::io_setup_x32 as usize] = Some(SyscallID::io_setup_x32);
    t[SyscallID::io_submit_x32 as usize] = Some(SyscallID::io_submit_x32);
    t[SyscallID::execveat_x32 as usize] = Some(SyscallID::execveat_x32);
    t[SyscallID::preadv2_x32 as usize] = Some(SyscallID::preadv2_x32);
    t[SyscallID::pwritev2_x32 as usize] = Some(SyscallID::pwritev2_x32);

    t
}

#[cfg(not(target_arch = "x86_64"))]
const fn build_id_to_syscall_table() -> [Option<SyscallID>; MAX_NUM_SYSCALLS] {
    compile_error!("non supported architecture");
}
